const router = require('express')?.Router();
const {
    getAutoGeneratedCaptionsFile,
    reuploadVideos
} = require('@controllers')?.videosControllers;

router.post('/text-tracks/auto-generated-captions', getAutoGeneratedCaptionsFile);

router.post('/reupload', reuploadVideos);

module.exports = router;
