const router = require('express')?.Router();
const {
    editEmbedDomains,
    getAutoGeneratedCaptionsFile,
    reuploadVideos
} = require('@controllers')?.videosControllers;
const { validateEditAction } = require('@middlewares');

router.post('/text-tracks/auto-generated-captions', getAutoGeneratedCaptionsFile);

router.post('/reupload', reuploadVideos);

router.put('/embed-domains/:action', [validateEditAction], editEmbedDomains); // Action options: 'overwrite', 'add', 'delete'.

module.exports = router;
