const router = require('express')?.Router();
const { getAutoGeneratedCaptionsFile } = require('@controllers')?.videosControllers;

router.post('/text-tracks/auto-generated-captions', getAutoGeneratedCaptionsFile);

module.exports = router;
