module.exports = {
    ACCEPT: { Accept: 'application/vnd.vimeo.*+json;version=3.4' },
    AUTHORIZATION: { Authorization: `Bearer ${process.env.VIMEO_PERSONAL_ACCESS_TOKEN}` },
    DEFAULT_EMBED_DOMAINS_LIST: [
        '82.223.3.92',
        'a3-191395075.cluster3.canvas-user-content.com',
        'alumniesade.com',
        'amara.org',
        'articulate.com',
        'basecamp.com',
        'berkeley.edu',
        'berkeleyextension.globalalumni.org',
        'berkeleyextensiononline.com',
        'boothexedonline.com',
        'campus.iese.edu',
        'campusesade.com',
        'canvas-user-content.com',
        'ccii.es',
        'ceudigital.com',
        'cluster3.canvas-user-content.com',
        'devceu.globalalumni.org',
        'digitalcourses-ga.xpro.mit.edu',
        'dub.scorm.canvaslms.com',
        'ecampus.esade.edu',
        'elucidat.com',
        'esade.edu',
        'esadeinon.instructure.com',
        'execedon.chicagobooth.edu',
        'globalalumni.instructure.com',
        'globalalumni.org',
        'globalalumni.xpromit.com',
        'globalcourses.xpro.mit.edu',
        'iad.scorm.canvaslms.com',
        'iese.edu',
        'inonesade.com',
        'learning.elucidat.com',
        'learningcampus.org',
        'mitpeonline.com',
        'mitpevirtualcampus.com',
        'myesade.esade.edu',
        'online.centrogarrigues.com',
        'online.esade.edu',
        'online.professional.uchicago.edu',
        'onlinelearning.berkeley.edu',
        'onlineprofessionaluchicago.com',
        'pablorivas.es',
        'profesional.uchicago.edu',
        'professional.uchicago.edu',
        'professionalprograms.mit.edu',
        'professionalprogramsmit.com',
        'programas.uclaextension.globalalumni.org',
        'programas.universidad-online-uees.com',
        'programas.usilmiami.com',
        'programasprofesionales.mit.edu',
        'prometheus.globalalumni.org',
        'rise.articulate.com',
        'scorm-iad-prod.insops.net',
        'spanish.xpro.mit.edu',
        'spanishcourses.xpro.mit.edu',
        'sts.iese.edu',
        'uchicago.edu',
        'uchicagodigital.com',
        'uclaextension.globalalumni.org',
        'uclaextensiononline.com',
        'usilonlife.com'
    ],
    DEFAULT_VIDEO_PRIVACY_SETTINGS: {
        view: 'disable', // The video is hidden from Vimeo.
        embed: 'whitelist', // The video can be embedded on specific domains.
        download: false,
        add: false,
        comments: 'nobody'
    },
    MAX_PAGE_RESULTS: 100,
    VIMEO_API_BASE_URL: 'https://api.vimeo.com'
};
