/**
 * Extracts the most recent auto-generated captions associated with a video from an array of text tracks. 
 * @param {Object[]} textTracks - Array of text track objects.
 * @param {string} video - The ID or name of the video.
 * @returns {Object} - An object containing the result of the extraction operation:
 * - `ok`: {boolean} - Indicates whether the operation was successful.
 * - `data`: {Object} - The most recent auto-generated captions object, if `ok` is `true`.
 * - `statusCode`: {number} - The status code associated with the error, if `ok` is `false`.
 * - `message`: {string} - The error message describing the reason for failure, if `ok` is `false`.
 */
const extractAutoGeneratedCaptions = (textTracks) => {

    try {

        const autoGeneratedCaptionsArr = textTracks
            .filter(({ type, name }) => type === 'captions' && name === 'auto_generated_captions.vtt')
            .sort((captions1, captions2) => captions2.id - captions1.id); // Sort in descending order so that the first caption is the most recent.

        // The array is empty.
        if (!autoGeneratedCaptionsArr.length) {

            throw new Error(`No auto-generated captions were found.`, { cause: { statusCode: 404 } });

        };

        return {
            ok: true,
            data: autoGeneratedCaptionsArr[0] // The first element of the sorted `autoGeneratedCaptionsArr` represents the most recent captions.
        };

    } catch (error) {

        console.error('\n' + error.message);

        const statusCode = error.cause?.statusCode ?? 500;

        return {
            ok: false,
            statusCode,
            message: error.message
        };

    };

};

module.exports = extractAutoGeneratedCaptions;
