const fetch = require('node-fetch');
const path = require('path');
const { extractAutoGeneratedCaptions } = require('@helpers');
const { getAllTextTracks } = require('@services')?.videosServices;
const { saveFileLocally } = require('@utils');

const getAutoGeneratedCaptionsFile = async (req, res) => {

    const failures = [], successes = [];

    try {

        const { body: { videos }, query: { fields } } = req;

        for (const video of videos) {

            console.log(`\nIterating over video ${video}...`);

            const textTracks = await getAllTextTracks(video, fields);

            if (!textTracks.ok) {

                const { ok, ...errorInfo } = textTracks;

                failures.push({ ...errorInfo, video });

                continue;

            };

            const autoGeneratedCaptions = extractAutoGeneratedCaptions(textTracks.data);

            if (!autoGeneratedCaptions.ok) {

                const { ok, ...errorInfo } = autoGeneratedCaptions;

                failures.push({ ...errorInfo, video });

                continue;

            };

            const { link } = autoGeneratedCaptions.data;

            const response = await fetch(link); // Get the auto-generated captions .vtt file.

            if (!response.ok) {

                const errorInfo = {
                    statusCode: response.status,
                    message: 'Failed to retrieve the auto-generated captions file.',
                    video
                };

                failures.push(errorInfo);

                continue;

            };

            const autoGeneratedCaptionsFile = await response.text();

            const folderPath = path.join(__dirname, '../', 'downloads', 'captions');

            const fileName = `${video}.vtt`;

            const saveFileProcess = await saveFileLocally(folderPath, fileName, autoGeneratedCaptionsFile);

            if (!saveFileProcess.ok) {

                const { ok, ...errorInfo } = saveFileProcess;

                failures.push({ ...errorInfo, video });

                continue;

            };

            console.log(`\nAuto-generated captions file of video ${video} successfully saved locally.`);

            successes.push(video);

        };

        const total = {
            videos: videos.length,
            successes: successes.length,
            failures: failures.length
        };

        console.log('\n', total ,'\n');

        res.status(200).json({ total, data: { successes, failures } });

    } catch (error) {

        console.error('\n', error, '\n');

        res.status(500).json({ message: error.message });

    };

}; //!GETAUTOGENERATEDCAPTIONSFILE-END

module.exports = { getAutoGeneratedCaptionsFile };
